language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: csae8092
  password:
    secure: AdXGoxrPqvVtsbpJp7G+ARkbT8BHVQu3wNNbB5a53Ruw3+OF9soPhRN6qLdN8gK4GZCm09sOJ4ortlQlMNyfrALclqUUzOLXv8UkRlAuohzL9Wu3iS9TRZBXRq2VT0NKtGtrir+8rmm6hjYn6XNou8SfY02sZCwOgX9ly649gLsf9/IB7xB450mcws64jWD9VK4WZqxLOy0oxYnwRhOAZuASrBptb/TviLu2q7Q6+9Q4MtDJjdMqoPJYeOIKvgh7fHDxHkd9yDRmJSZKjN4ztYoji0VsKvOMjscOnCcbRx765zcNrilz7EdscAmxtMbp3oMnDily211rzaHVli0Fu+JUL58X0dnJgxxWYlRYMDg/tc/dmMJFUNJJRp01Ssla3OU589LKbrwf3+ztVSFcw29qdV24C+YWQ55Vg9rSUSNbRWHfeo2auwIWIbABPYAUn7hQoE26eER0yTktm5arue4KZRQCcIKmRzQSccDO6pp/vC6EvrCivxjvqpi6E92ptEJvKGvX9HENlfSDYQkCZrpfgc43oH1ccAPpYGUyOMG1hRsN3cWYpKOx1HmkBuv6yn33ErWeLvcPT/2EX2WL1oact887+dmVmTMcKldyYiNq3VRTOLyJ8/+W4XQEKEWINn4f7mvtTfD4SB1hAcEs2QRcI1dAIgynlXPGnv5iZPM=
  on:
    tags: true
    repo: acdh-oeaw/freud_api_crawler
    python: 3.8
