language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: csae8092
  password:
    secure: GtOgpE8bPF0SPKj8KfAeslUk3z5u/tFzkg5x3OvfC6+TsKr12v8Z46MfAfA67s6iapiTo2f7ldOq9YzfFN4XsGIV8sYpBWlP/dMhPBvVl0J1H19aryOeVR7GD+YGWJqpEEb2LSQF5vYOxSoxFMWoD3/g62qA01CwvboOm8r1YXwRIr8cq2B2aAzA/XAQEv4FjVvbC9pYPbErcAxeaZLWZ2Lx9KUMakkTrG2QUcMa5F/1alaSy6UsKK+cSN60ihqosvW86qBn3bKs53l5/sz6dwt8Thps/RsUpQ0G+cZaHK6GDI7HmRQdrwGtEkMzBcuxmkV6eEeUYXD0ztQxcGaYGhAMpp7/lmBwCzOTpTkidGmJrRtQNtJkk6VHih2dG9S5cM9+CI9DGJFjpWwNbW5/1K4RVq0yHunF/X9yVI6meJ8+5w6M3uEDSMZhRzkMEGWPrLzCBVI44A9SYOR9q9/ud0lWN30y4wKmnWdmbJoD07q7oLxkYoQcz5qhq+rnJW+u4viQRqMHljcZ9kB0OqMwSiHOLH80ygXASodv1484SONZ8/9j09sWaJ/m/jl7i+/aY3EpPJ3RTRwMpIKt7tcOg7kjwZp2G8F77s0a3g5IvPRzP/9/pECG5PIYT5fRRW4G931/DCScA7Fcu8xFTdt+hrEsyq6B5/ZiTPSXNkwArE8=
  on:
    tags: true
    repo: acdh-oeaw/freud_api_crawler
    python: 3.8
env:
  global:
  - secure: LKcILaJS2gWBrE//5X1nOK7sZY7hR7QBKWtgW7V0DxwSOIPe4CuiKrOXf+rkzP3Knk27gqCGsuHmTaaDm7pp6vehzO93UW8PhAiRAyeXaSU8FOArwVSVKJ25Gk+x8xLQzGQCC3jOW6l7h/0blO/KiHKslqgvw5Y1bk/8IqbZCuV7wlCEDFkax6RUTzAGf+gwxQZ5wu97XhKXBIq4d0VsiEyfvXzTiEqlMMsB/aXf23JVQufF9EACXjLHhpASosUFrNCyb5mKwLpzgwZS6m0+AONRinrfAdX4nmxXXGjouH3maB/oU5Kb1cCbAckHxUYMzjOmp3UrzM6ZkeMijPIXN+W5f+w8KCF2YJ+nL92+k8b8yV9CTrhJMiRnOkmUaYICFxOCW8ciN4wRG7aDxSBppLtvqdpSoWS3dG+GnEL5V/DppPHY7nfT+Xh6bZQidHVBGbVDRmO5IWRKnCNB3QVoWUfp3psMYj1TzP61ji+GAZ8O3N5nTXIKVR18sX0u+D+1FyNWGxbYakY/UkBLuNJ0SNrVMBz9nWvDI3Sq/ZulGUF6VOEPDgwj56UF5DBB+9ix9Sdkfk0b01t1kqsjrm7FqzXOEGVvW+xIN8JkFqVRBaBBhtBTqE1V18bzPDpXXWQybn6AAsnXo0/WLwt9V9VqNVU69ikoyY/uyHArA6fByr8=
  - secure: WcgB0191ydXgTZLCEdLbiaRajzB/9L7ymrPAubiyDRt7g6DyI+x9X6Gltqm/abD/dhY+GVxnFT7rzgIgn0PNNUW9pU4ovVnHQ9qRhVNPlbwYEYW60od7KIQ33CFHhTuUAYikcxrAXYJnG5uBxXTZHNUs/GeRmm2eJa70H1t027O0X+t4hTrCMYdTwPsisCTdtQEBoO0ICJe8NmDMjHoq+ULJcoGAlfjg7TOfjUO8kiPvH1fUPcqzI24xNIi5U155ZZdu4+X7gn9AV+w0aTJAWUoaalinsBZgABDE4IhXI0DWTz11EFA6cvG4yNulA/2AOHPGF2SsdcP533xkVL3sTNfsUqAG+vFgBcbp2AgSkV6lnBswDQrO1loP1nGaSsvmc4zWDD57wcjjT3xaVqMVgwGt/hf0cDhDYECyvA8gEcaSCKMZEyG+FP7Cd9RxmUKoHRwBmuKxh/C7kYrGHAIuIuV8nRcfXLzZLfbNo4leUAVwNvz15Hccw0hno1CiIB0rr9yRAcq5Zgv79UWU0sCR+bUaM9g4Sr3hMo9sIO7mK7MXusuvmt2bes3D6NF8lt5val+b9LYfm/H5bIp+98wx5B72PDIYrF6xlQQADSATkEm088GkSNZQxYVG6J+BZvjWWSwmZvpnOxhyC3wqfB7CpplahHIBO9bAV9Pc4bU+rqo=
