language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: csae8092
  password:
    secure: GtOgpE8bPF0SPKj8KfAeslUk3z5u/tFzkg5x3OvfC6+TsKr12v8Z46MfAfA67s6iapiTo2f7ldOq9YzfFN4XsGIV8sYpBWlP/dMhPBvVl0J1H19aryOeVR7GD+YGWJqpEEb2LSQF5vYOxSoxFMWoD3/g62qA01CwvboOm8r1YXwRIr8cq2B2aAzA/XAQEv4FjVvbC9pYPbErcAxeaZLWZ2Lx9KUMakkTrG2QUcMa5F/1alaSy6UsKK+cSN60ihqosvW86qBn3bKs53l5/sz6dwt8Thps/RsUpQ0G+cZaHK6GDI7HmRQdrwGtEkMzBcuxmkV6eEeUYXD0ztQxcGaYGhAMpp7/lmBwCzOTpTkidGmJrRtQNtJkk6VHih2dG9S5cM9+CI9DGJFjpWwNbW5/1K4RVq0yHunF/X9yVI6meJ8+5w6M3uEDSMZhRzkMEGWPrLzCBVI44A9SYOR9q9/ud0lWN30y4wKmnWdmbJoD07q7oLxkYoQcz5qhq+rnJW+u4viQRqMHljcZ9kB0OqMwSiHOLH80ygXASodv1484SONZ8/9j09sWaJ/m/jl7i+/aY3EpPJ3RTRwMpIKt7tcOg7kjwZp2G8F77s0a3g5IvPRzP/9/pECG5PIYT5fRRW4G931/DCScA7Fcu8xFTdt+hrEsyq6B5/ZiTPSXNkwArE8=
  on:
    tags: true
    repo: acdh-oeaw/freud_api_crawler
    python: 3.8
