language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: fvq9y975AdK+dKsS8ecSyJ44b0Fbj1FpctDvPm230is4HVoSxw9MSgKMnVcvXGD60fu4mFjy8YxIa93JlzRdJra0OPKAFPJoPj3FWWHzX4FVp4+00itiBeXJU4nWr9VNaY3GKGj5/OLlxDy6jHop5vtJhSFBc486Zjdc/P7AKe3jhYNnwieaaHrPUv4+FCsNjm2DhZG8aE8FJJwtFtLiEQ93k7nxz8WwXGTW4XtvIXypey1vtAO27N91NoxhMe5xBu/kb0p4iG0W4idrxF0IQDAFvk7peNJdG1nBDKajO1mc9dEGlE1dRJDjQLS15es0vmij0rr9XLjeSEENWHhDTqgtIK2lNUmQuS5cJ+N1sVxwu/BZATrgQOEOeIwuOWSS/d1QB23tCJeeSxNOgu71JvWW+M4LfDGExh+EW8Etg6WvLecpGvEKQcaPSzQg3U9EAssxdK+vgZQsoTAXzR9c8PtmIqozTDFs6aNj0GzA199+uKYGsxqxk0TRhSsz0Mu4C8WAsYAuoVDzConRjmwW/bb0Wb5omlBBMOE6sWHqLeLUNUMqs/EzEWm4q5MLwyPstR5IBlrRLlMMKoDegXSI+4lBkqlu7+fAcYEKhoD11eVC1W/RF/9vBCG5s0YJ1OvUGn1o6Y5uWIRHBM4ZtUNPD/+0xgw6oGuAGybmLeaDzWI=
  on:
    tags: true
    repo: acdh-oeaw/freud_api_crawler
    python: 3.8
env:
  global:
  - secure: BIH8GYd8++8E2n9YxzBJQ1gKKrfDmxl0ZlwthLYbu4OGTVU0QDCT1Awv8r9ANAQkFaL48yUhvm6M4GpjALIynA28la42YEcdJrTF8XwnoPYTA0Z/FjARdt2463yxzO+V/5fbC0lkgvM6zk0zP67FWk8mR3H5WOwqZq+TZSi2y2YfFmR1LpGkEum6AftLH4aAoQuvx3cgFoIBf+5XiKU8fCnnmmFlUQiHHocFxMb6Ay6bEYcO5VMXIIcduP2JijKEt2rGFtNS0NrMN+vzdmF/7ywpyZ0VPglFabQtdpO6mhEBSASAcy5Sw6cHxE51XtDl/ktpi+i3ozqhKzUwKuPwKU2VwHuOaMc/6KAy0sRL1v0k1cacAkRAIwntR0JkFidf/pbMZBjiiqIEVBhGaQFa/RNwmyibYuznuYP0W/DLg24WEqrVhHXkdoNoS9O5605Bs7nqjAe5Ue8IfMSbjs7EWCLGCYK/b/Z/FcDVtKXGqNb7/qDMhkhxuk7UOF3Kb+bRHdghla8pfAiZqL/Lr4Ye2diFIUoWDh24/zto2Tt/l+PLhqyWDM9WO3X22838wB03m/Iw8zvCcEgFdICjbL3nTRpaKa2aqSFqy3mnf7u6EGN7+StTxYbxwcdQ9q9tJwn+BoVFIFrQY0j10DoWicczri8ZArHHMi9vQ8ZVgg1qFAA=
  - secure: CUdtWq5iV65/qGFn0nig2PhnnnVYaVWjOduqD34tdkDphmWrcNs13kY/07HqKlh6d3dPIsQgEuT7KKvspFmJYUgt78jSj+HEaQKCW3JuqeNLs5zIOc/W8kmRtbSF+guDKHSsNpd0nis3zfqzQVUYIURPFr4XsnYfEBfFxMzLuw4YySit6SlO5nQjXpod9qyKx+fX7xYQoyDhhcRl0VDx4iuAhuUf31eK4bCSs14OjW+YcP3Eea2BwQh5b0x/h5aLtkx64npayzeVoXjlz3312e/myJJHOVoIyLAjeAVTx5df1KicuectiAgy4RnIxuk8URCn419JAX64cedSI35h6hctJV7qQRwQ7SV8w8/PJP9MmUV+to2WTlHczgmqJr5SnvJv/iRDVi9K86Df4z0GnqhejZnmrdceO0AdQadEo+6SMa/rqzlyvzhLRj/DgcezFryUmJuw4ZdUjEQmhohrIUxDcwxNPdsD2Q0c+TOrG7RuvB8hPp4NpYHW/AsFTVL/OIBYpMSwLFxB71MJRdl9Dfn3MDcYclpQba5okSvtiVA5fFqHQypifgo8xWRY9sdA3+77i7EZ9ZiQqK/Y0zQ8WXU1kBS1h4+e4AUUtWce9pzSaWw1rH1ZLI92PDogaAfsRf5lxz+b4wgkibJFex4cbMXN4vuHcQJiqN180D9u440=
